In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

print("pandas version:", pd.__version__)
print("numpy version:", np.__version__)

pandas version: 2.3.1
numpy version: 1.26.4

In [2]:
df = pd.read_csv("/Users/jein/Downloads/ONINE_FOOD_DELIVERY_ANALYSIS.csv")

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Order_ID             100000 non-null  object
 1   Customer_ID          100000 non-null  object
 2   Customer_Age         49907 non-null   float64
 3   Customer_Gender      75144 non-null   object
 4   City                 83274 non-null   object
 5   Area                 83315 non-null   object
 6   Restaurant_ID        100000 non-null  object
 7   Restaurant_Name      100000 non-null  object
 8   Cuisine_Type         83115 non-null   object
 9   Order_Date           98986 non-null   object
 10  Order_Time           98002 non-null   object
 11  Delivery_Time_Min    66641 non-null   float64
 12  Distance_km          66530 non-null   float64
 13  Order_Value          66673 non-null   float64
 14  Discount_Applied     83285 non-null   float64
 15  Final_Amount         44303 non-null   float64
 16  Payment_Mode         80089 non-null   object
 17  Order_Status         100000 non-null  object
 18  Cancellation_Reason  9031 non-null    object
 19  Delivery_Partner_ID  100000 non-null  object
 20  Delivery_Rating      83477 non-null   float64
 21  Restaurant_Rating    100000 non-null  float64
 22  Order_Day            100000 non-null  object
 23  Peak_Hour            67038 non-null   object
 24  Profit_Margin        100000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 19.1+ MB
None

In [4]:


print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)

Shape: (100000, 25)

Data Types:
 Order_ID                object
Customer_ID             object
Customer_Age           float64
Customer_Gender         object
City                    object
Area                    object
Restaurant_ID           object
Restaurant_Name         object
Cuisine_Type            object
Order_Date              object
Order_Time              object
Delivery_Time_Min      float64
Distance_km            float64
Order_Value            float64
Discount_Applied       float64
Final_Amount           float64
Payment_Mode            object
Order_Status            object
Cancellation_Reason     object
Delivery_Partner_ID     object
Delivery_Rating        float64
Restaurant_Rating      float64
Order_Day               object
Peak_Hour               object
Profit_Margin          float64
dtype: object

In [5]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())



print("\nTotal missing values in dataset:", df.isnull().sum().sum())

Missing values per column:
Order_ID                   0
Customer_ID                0
Customer_Age           50093
Customer_Gender        24856
City                   16726
Area                   16685
Restaurant_ID              0
Restaurant_Name            0
Cuisine_Type           16885
Order_Date              1014
Order_Time              1998
Delivery_Time_Min      33359
Distance_km            33470
Order_Value            33327
Discount_Applied       16715
Final_Amount           55697
Payment_Mode           19911
Order_Status               0
Cancellation_Reason    90969
Delivery_Partner_ID        0
Delivery_Rating        16523
Restaurant_Rating          0
Order_Day                  0
Peak_Hour              32962
Profit_Margin              0
dtype: int64

Total missing values in dataset: 461190

In [6]:
print("\nPercentage of missing values:")
print((df.isnull().sum() / len(df)) * 100)

Percentage of missing values:
Order_ID                0.000
Customer_ID             0.000
Customer_Age           50.093
Customer_Gender        24.856
City                   16.726
Area                   16.685
Restaurant_ID           0.000
Restaurant_Name         0.000
Cuisine_Type           16.885
Order_Date              1.014
Order_Time              1.998
Delivery_Time_Min      33.359
Distance_km            33.470
Order_Value            33.327
Discount_Applied       16.715
Final_Amount           55.697
Payment_Mode           19.911
Order_Status            0.000
Cancellation_Reason    90.969
Delivery_Partner_ID     0.000
Delivery_Rating        16.523
Restaurant_Rating       0.000
Order_Day               0.000
Peak_Hour              32.962
Profit_Margin           0.000
dtype: float64

In [7]:
print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [8]:
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
0,ORD000001,CUST6948,19.0,Male,NaN,Central,RES936,Restaurant_29,Chinese,10/20/2024,...,NaN,UPI,Delivered,NaN,DP563,5.0,4.4,Weekend,True,0.13
1,ORD000002,CUST6515,NaN,Female,Chennai,North,RES689,Restaurant_419,Chinese,08/12/24,...,4849.0,COD,Delivered,NaN,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,NaN,Male,Delhi,NaN,RES723,Restaurant_244,Arabian,12/08/24,...,737.0,Wallet,Delivered,NaN,DP580,4.0,4.9,Weekend,True,0.08
3,ORD000004,CUST2744,NaN,Male,Mumbai,Central,RES951,Restaurant_178,Chinese,10/08/24,...,NaN,UPI,Cancelled,Late Delivery,DP155,2.0,3.4,Weekday,NaN,0.04
4,ORD000005,CUST4389,57.0,Female,Chennai,South,RES419,Restaurant_262,Chinese,02/04/24,...,352.0,Card,Delivered,NaN,DP728,2.0,4.4,Weekend,False,0.12

In [9]:
# fill with specific values
df['Customer_Gender'] = df['Customer_Gender'].fillna('Unknown')
df['City'] = df['City'].fillna('Not specified')

In [10]:
# Age with average
df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].mean())
df["Customer_Age"] = df["Customer_Age"].round().astype(int)
# Fill Cuisine Type with most Frequent value
df['Cuisine_Type'] = df['Cuisine_Type'].fillna(df['Cuisine_Type'].mode()[0])

In [12]:
df[["Customer_Age"]].head()

   Customer_Age
0            19
1            39
2            39
3            39
4            57

In [ ]:
# Handle high missing values

df['Cancellation_Reason'] = df['Cancellation_Reason'].fillna('Not cancelled')

In [14]:
print(df['Cancellation_Reason'].isnull().sum())

0

In [15]:
# Area- Fill with mode
df['Area'] = df['Area'].fillna(df['Area'].mode()[0])
# Distance_km - Fill with median(robust to outliers)
df['Distance_km'] = df['Distance_km'].fillna(df['Distance_km'].median())
#Peak_Hour-fill with mode 
df['Peak_Hour'] = df['Peak_Hour'].fillna(df['Peak_Hour'].mode()[0])
#Delivery_Rating - fill with median or 0
df['Delivery_Rating'] = df['Delivery_Rating'].fillna(df['Delivery_Rating'].median())
# Order_Date', 'Order_Time - Better to drop these rows
df.dropna(subset=['Order_Date', 'Order_Time'], inplace=True)
# Drop rows where essential info is missing
df.dropna(subset=['Final_Amount'], inplace=True)

In [16]:

# # Missing Values
df['Delivery_Time_Min'] = df['Delivery_Time_Min'].fillna(df['Delivery_Time_Min'].median())
df['Order_Value'] = df['Order_Value'].fillna(df['Order_Value'].median())
df['Payment_Mode'] = df['Payment_Mode'].fillna(df['Payment_Mode'].mode()[0])

In [17]:
print("\nPercentage of missing values:")
print((df.isnull().sum() / len(df)) * 100)

Percentage of missing values:
Order_ID               0.0
Customer_ID            0.0
Customer_Age           0.0
Customer_Gender        0.0
City                   0.0
Area                   0.0
Restaurant_ID          0.0
Restaurant_Name        0.0
Cuisine_Type           0.0
Order_Date             0.0
Order_Time             0.0
Delivery_Time_Min      0.0
Distance_km            0.0
Order_Value            0.0
Discount_Applied       0.0
Final_Amount           0.0
Payment_Mode           0.0
Order_Status           0.0
Cancellation_Reason    0.0
Delivery_Partner_ID    0.0
Delivery_Rating        0.0
Restaurant_Rating      0.0
Order_Day              0.0
Peak_Hour              0.0
Profit_Margin          0.0
dtype: float64

In [18]:

for col in ['Delivery_Time_Min', 'Order_Value']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df[col] = np.clip(df[col], Q1 - 1.5*IQR, Q3 + 1.5*IQR)

We cap instead of delete because extreme orders can be real.

In [19]:
print("\nPercentage of missing values:")
print((df.isnull().sum() / len(df)) * 100)

Percentage of missing values:
Order_ID               0.0
Customer_ID            0.0
Customer_Age           0.0
Customer_Gender        0.0
City                   0.0
Area                   0.0
Restaurant_ID          0.0
Restaurant_Name        0.0
Cuisine_Type           0.0
Order_Date             0.0
Order_Time             0.0
Delivery_Time_Min      0.0
Distance_km            0.0
Order_Value            0.0
Discount_Applied       0.0
Final_Amount           0.0
Payment_Mode           0.0
Order_Status           0.0
Cancellation_Reason    0.0
Delivery_Partner_ID    0.0
Delivery_Rating        0.0
Restaurant_Rating      0.0
Order_Day              0.0
Peak_Hour              0.0
Profit_Margin          0.0
dtype: float64

In [21]:

# Cancelled orders should not have ratings-Invalid Values

df['Delivery_Rating'] = df['Delivery_Rating'].clip(0, 5)
df['Restaurant_Rating'] = df['Restaurant_Rating'].clip(0, 5)
df = df[df['Profit_Margin'] >= 0]

df.loc[df['Order_Status'] == 'Cancelled',
       ['Delivery_Rating', 'Restaurant_Rating']] = np.nan

In [22]:
df.head()

,Order_ID,Customer_ID,Customer_Age,Customer_Gender,City,Area,Restaurant_ID,Restaurant_Name,Cuisine_Type,Order_Date,...,Final_Amount,Payment_Mode,Order_Status,Cancellation_Reason,Delivery_Partner_ID,Delivery_Rating,Restaurant_Rating,Order_Day,Peak_Hour,Profit_Margin
1,ORD000002,CUST6515,39,Female,Chennai,North,RES689,Restaurant_419,Chinese,08/12/24,...,4849.0,COD,Delivered,Not cancelled,DP369,5.0,4.7,Weekday,True,0.48
2,ORD000003,CUST1765,39,Male,Delhi,South,RES723,Restaurant_244,Arabian,12/08/24,...,737.0,Wallet,Delivered,Not cancelled,DP580,4.0,4.9,Weekend,True,0.08
4,ORD000005,CUST4389,57,Female,Chennai,South,RES419,Restaurant_262,Chinese,02/04/24,...,352.0,Card,Delivered,Not cancelled,DP728,2.0,4.4,Weekend,False,0.12
7,ORD000008,CUST5865,39,Male,Not specified,North,RES696,Restaurant_41,Chinese,5/26/2024,...,3486.0,UPI,Delivered,Not cancelled,DP316,5.0,3.8,Weekend,False,0.18
8,ORD000009,CUST4356,39,Other,Delhi,Central,RES780,Restaurant_155,Italian,09/07/24,...,425.0,Wallet,Delivered,Not cancelled,DP531,2.0,3.7,Weekend,True,0.08

In [23]:
print(df.columns)

Index(['Order_ID', 'Customer_ID', 'Customer_Age', 'Customer_Gender', 'City',
       'Area', 'Restaurant_ID', 'Restaurant_Name', 'Cuisine_Type',
       'Order_Date', 'Order_Time', 'Delivery_Time_Min', 'Distance_km',
       'Order_Value', 'Discount_Applied', 'Final_Amount', 'Payment_Mode',
       'Order_Status', 'Cancellation_Reason', 'Delivery_Partner_ID',
       'Delivery_Rating', 'Restaurant_Rating', 'Order_Day', 'Peak_Hour',
       'Profit_Margin'],
      dtype='object')

In [24]:
# Save cleaned data
df = df.to_csv("cleaned_data.csv", index=False)